Feature/idskrp 138 implement table component
id-sk/id-sk-frontend pull request #326
Opened 2021-11-18 10:14 UTC by adriKosa

2021-11-18 15:03 UTC, TenTibor requested changes

2021-11-18 15:03 UTC, TenTibor commented on src/idsk/components/table/table.yaml
> +
Zbytočná medzera.
Podľa vzorov ostatných yaml files, by medzera mala vizualne oddeliť examples od seba

2021-11-18 15:03 UTC, TenTibor commented on src/idsk/components/table/table.yaml
> +
Zbytočná medzera.
Podľa vzorov ostatných yaml files, by medzera mala vizualne oddeliť examples od seba

2021-11-18 15:59 UTC, TenTibor approved these changes

2021-11-19 08:12 UTC, LubosKat commented on src/idsk/components/table/template.njk
> +    <div class="idsk-table__heading-with-caption">
- tato classa vyzera ze sa v scss ani nepouziva, neviem ci ma vyznam.
- plus mozno by trebalo pred div-ko vybrat if (title or caption) lebo ak nebude ani jedno ani druhe bude zbytocne prazdne divko

2021-11-19 09:21 UTC, LubosKat commented on src/idsk/components/table/template.njk
> +    <div class="idsk-table__heading-with-caption">
plus su tu nejake merge confilicty ta este pls prve pullni dev. Najskor asi tie yaml refactor veci to sposobili

2021-11-19 09:53 UTC, merged